

jwt:
  secret: f336280f7fb039ab6abaa5e7b9c3c80c8605c50acc988236e376ca3f7cca0bd7
  expirationMs: 3600000
  refreshExpirationMs: 86400000

spring:
  application:
    name: team-project

  datasource:
    url: jdbc:mysql://localhost:3306/team
    username: root
    password: "0304"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: true
server:
  port: 8081